---

- hosts: database
  become: true
  vars_files:
    - vars/database.yml
  roles:
    # Database install
    - role: geerlingguy.mysql
      when: dbengine == 'mysql'
    - role: geerlingguy.postgresql
      when: dbengine == 'postgres'

