---

- hosts: database
  become: true
  vars_files:
    - vars/database.yml
  roles:
    # Database install
    - name: geerlingguy.mysql

- hosts: webserver
  become: true
  vars:
  vars_files:
    - vars/database.yml
  pre_tasks:
    - name: Import Moodle PHP Setup role to set the web server config
      import_role:
        name: call-learning.moodle
        tasks_from: phpsql-setup
  roles:
    # Then apache
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    # Then PHP Database libraries
    - name: geerlingguy.php-mysql
    # Other dependencies such as composer
    - name: geerlingguy.composer
    - name: geerlingguy.git
    - name: geerlingguy.certbot
    - name: call-learning.moodle
