---
- src: geerlingguy.repo-remi
- src: geerlingguy.apache
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.postgresql
- src: geerlingguy.mysql
- src: geerlingguy.php
- src: geerlingguy.php-versions
- src: geerlingguy.php-pgsql
- src: geerlingguy.php-mysql
- src: geerlingguy.git
- src: geerlingguy.certbot
- src: geerlingguy.composer
- src: geerlingguy.certbot
- src: https://github.com/call-learning/ansible-role-moodle.git
  name: call-learning.moodle
  version: laurent/fix-ci
