---

# Some essential logic here for:
# - Python interpreter
# - Bastion host
# - Gatewayed host (in a private network only accessible through bastion)
all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_user: "ansible"
    ansible_ssh_private_key_file: "~/.ssh/id_imt_training_rsa"
#  hosts:
#    moodle41:
#      ansible_host: 10.0.0.99
  children:
    moodletest:
      hosts:
        moodle1:
        moodle2:
        moodle3:
        moodle4:
        moodle5:
        moodle6:
        moodle7:
        moodle8:
        moodle9:
    webserver:
      hosts:
        moodle1:
        moodle2:
        moodle3:
        moodle4:
        moodle5:
        moodle6:
        moodle7:
        moodle8:
        moodle9:
        moodle40:
        moodle41:
    database:
      hosts:
        moodle1:
        moodle2:
        moodle3:
        moodle4:
        moodle5:
        moodle6:
        moodle7:
        moodle8:
        moodle9:
        moodle40:
        moodle41:
