---

# Some essential logic here for:
# - Python interpreter
# - Bastion host
# - Gatewayed host (in a private network only accessible through bastion)
all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_user: "ansible"
    ansible_ssh_private_key_file: "~/.ssh/id_imt_training_rsa"
  hosts:
    moodle1:
  children:
    webserver:
      hosts:
        moodle1:
        moodle40:
    database:
      hosts:
        moodle1:
        moodle40:
