---

mysql_databases:
  - name: "{{ moodle_database.dbname }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
mysql_users:
  - name: "{{ moodle_database.dbuser }}"
    host: "%"
    password: "{{ moodle_database.dbpass }}"
    db: "{{ moodle_database.dbname }}"
    priv: "{{ moodle_database.dbname }}.*:ALL"
    encrypted: false
database_server_host: "{{ domain_name }}"
