---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    force: false
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: testinstance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - database
      - webserver
    etc_hosts: "{'moodle.test':  '127.0.0.1'}"
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../../playbook.yml
  inventory:
    links:
      group_vars: ../../inventory/group_vars/
      host_vars: ../../inventory/host_vars/
scenario:
  name: default
verifier:
  name: ansible
