---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    force: false
driver:
  name: docker
platforms:
  - name: singleinstance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - database
      - webserver
    port_bindings:
      80: 80
      443: 443
    published_ports:
      - 0.0.0.0:80:80/tcp
      - 0.0.0.0:443:443/tcp
    etc_hosts:
      "${INSTANCE_DOMAIN_NAME:-ansible1.call-learning.io}" : "127.0.0.1"
provisioner:
  name: ansible
  env:
    DOMAIN_URL: "${INSTANCE_DOMAIN_NAME:-ansible1.call-learning.io}"
  log: true
  playbooks:
    converge: ../../playbook.yml
  inventory:
    links:
      group_vars: ../../inventory/group_vars/
      host_vars: ../../inventory/host_vars/
scenario:
  name: single
